minimum_pre_commit_version: "4.6.2"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: b82a6c8896e491b9cb377a99ff3412131920681b # v0.23.2
    hooks:
      - id: markdownlint-cli2
        language_version: "24.18.1"

  - repo: https://github.com/lycheeverse/lychee
    rev: 2bba271688c1abb1503097a064e6c3bc1d1b6a9b # lychee-v0.24.2
    hooks:
      - id: lychee-system
        types: [markdown]
        args: [--offline, --include-fragments, --no-progress]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb # v0.16.8
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
